# Generated by Django 4.2.6 on 2024-04-17 19:58

from django.db import migrations


def create_genres(apps, schema_editor):
    Genre = apps.get_model('assessment', 'Genre')

    genre_names = ['Action', 'Adventure', 'Animated', 'Comedy', 'Drama', 'Fantasy', 'Horror', 'RomCom']

    for name in genre_names:
        Genre.objects.create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_genre_alter_movie_year_released_movie_genres'),
    ]

    operations = [
        migrations.RunPython(create_genres),
    ]
